### ISSUE TITLE
@jvcasillas

### ISSUE THREAD

**Issue by hdmetz** [hdmetz/pa_2_issue#2]
@jvcasillas

**Comment by jvcasillas** [comment]
Ok. I took a look. You need to pay special attention to the instructions in 3 and 4. You have some naming issues, which is causing errors downstream. Make sure your wavs and textgrids are named appropriately and check your path (you are telling praating to look inside a folder called segmented, but you haven't created that... you have a folder called master).

**Comment by hdmetz** [comment]
Ok, thank you so much for your help. I will take a look at it.

Best,
Hunter

**Comment by hdmetz** [comment]
Hi Prof. Casillas,

Thank you! You helped me figure it out, it was just a simple naming mistake.

Best,
Hunter
